# Generated by Django 2.2.4 on 2019-08-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=100)),
                ('store', models.CharField(choices=[('LOBLAWS', 'Loblaws'), ('WALMART', 'Walmart'), ('AMAZON', 'Amazon')], max_length=7)),
                ('product_code', models.CharField(max_length=100)),
                ('product_code_type', models.CharField(choices=[('LOBLAWS', 'Loblaws'), ('WALMART', 'Walmart'), ('AMAZON', 'Amazon')], max_length=7)),
                ('nutrition_available', models.BooleanField(default=False)),
                ('ingredients_available', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('date_collected', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='AmazonProduct',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Product')),
            ],
            options={
                'verbose_name': 'Amazon Product',
                'verbose_name_plural': 'Amazon Products',
            },
        ),
        migrations.CreateModel(
            name='LoblawsProduct',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Product')),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_directory', models.CharField(blank=True, max_length=500)),
                ('breadcrumbs', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Loblaws Product',
                'verbose_name_plural': 'Loblaws Products',
            },
        ),
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Product')),
                ('total_size', models.CharField(blank=True, max_length=100)),
                ('serving_size_raw', models.CharField(blank=True, max_length=100)),
                ('serving_size', models.IntegerField(blank=True)),
                ('serving_size_units', models.CharField(blank=True, choices=[('g', 'grams'), ('mL', 'millilitres')], max_length=11)),
                ('ingredients', models.TextField(blank=True)),
                ('calories', models.IntegerField(blank=True)),
                ('sodium', models.FloatField(blank=True)),
                ('sodium_dv', models.FloatField(blank=True)),
                ('calcium', models.FloatField(blank=True)),
                ('calcium_dv', models.FloatField(blank=True)),
                ('total_fat', models.FloatField(blank=True)),
                ('total_fat_dv', models.FloatField(blank=True)),
                ('monounsaturated_fat', models.FloatField(blank=True)),
                ('polyunsaturated_fat', models.FloatField(blank=True)),
                ('saturated_fat', models.FloatField(blank=True)),
                ('saturated_fat_dv', models.FloatField(blank=True)),
                ('trans_fat', models.FloatField(blank=True)),
                ('trans_fat_dv', models.FloatField(blank=True)),
                ('potassium', models.FloatField(blank=True)),
                ('potassium_dv', models.FloatField(blank=True)),
                ('total_carbohydrate', models.FloatField(blank=True)),
                ('total_carbohydrate_dv', models.FloatField(blank=True)),
                ('dietary_fibre', models.FloatField(blank=True)),
                ('dietary_fibre_dv', models.FloatField(blank=True)),
                ('sugars', models.FloatField(blank=True)),
                ('sugars_dv', models.FloatField(blank=True)),
                ('protein', models.FloatField(blank=True)),
                ('cholesterol', models.FloatField(blank=True)),
                ('vitamin_a', models.FloatField(blank=True)),
                ('vitamin_a_dv', models.FloatField(blank=True)),
                ('vitamin_c', models.FloatField(blank=True)),
                ('vitamin_c_dv', models.FloatField(blank=True)),
                ('vitamin_d', models.FloatField(blank=True)),
                ('vitamin_e', models.FloatField(blank=True)),
                ('niacin', models.FloatField(blank=True)),
                ('vitamin_b6', models.FloatField(blank=True)),
                ('folacin', models.FloatField(blank=True)),
                ('folate', models.FloatField(blank=True)),
                ('vitamin_b12', models.FloatField(blank=True)),
                ('pantothenic_acid', models.FloatField(blank=True)),
                ('pantothenate', models.FloatField(blank=True)),
                ('alcohol', models.FloatField(blank=True)),
                ('carbohydrate', models.FloatField(blank=True)),
                ('erythritol', models.FloatField(blank=True)),
                ('glycerol', models.FloatField(blank=True)),
                ('isomalt', models.FloatField(blank=True)),
                ('lactitol', models.FloatField(blank=True)),
                ('maltitol', models.FloatField(blank=True)),
                ('mannitol', models.FloatField(blank=True)),
                ('polydextrose', models.FloatField(blank=True)),
                ('sorbitol', models.FloatField(blank=True)),
                ('xylitol', models.FloatField(blank=True)),
                ('iron', models.FloatField(blank=True)),
                ('iron_dv', models.FloatField(blank=True)),
                ('riboflavin', models.FloatField(blank=True)),
                ('selenium', models.FloatField(blank=True)),
                ('magnesium', models.FloatField(blank=True)),
                ('phosphorus', models.FloatField(blank=True)),
                ('thiamine', models.FloatField(blank=True)),
                ('zinc', models.FloatField(blank=True)),
                ('nutrition_raw_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Product Nutrition',
                'verbose_name_plural': 'Product Nutrition',
            },
        ),
        migrations.CreateModel(
            name='WalmartProduct',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='database.Product')),
            ],
            options={
                'verbose_name': 'Walmart Product',
                'verbose_name_plural': 'Walmart Products',
            },
        ),
    ]
