# Generated by Django 2.2.4 on 2020-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='omega3fattyacids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='omega3fattyacids',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
