# Generated by Django 2.2.4 on 2019-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_collected',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_code_type',
        ),
        migrations.AddField(
            model_name='product',
            name='scrape_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='upc_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition_available',
            field=models.BooleanField(blank=True),
        ),
    ]
