# Generated by Django 3.0.6 on 2020-06-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200526_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_history', to='database.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='most_recent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='most_recent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_code',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=500),
        ),
    ]
