# Generated by Django 2.2.4 on 2019-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190815_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loblawsproduct',
            name='breadcrumbs',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='loblawsproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loblawsproduct',
            name='image_directory',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loblawsproduct',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loblawsproduct',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='alcohol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='calcium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='calcium_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='carbohydrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='cholesterol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='dietary_fibre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='dietary_fibre_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='erythritol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='folacin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='folate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='glycerol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='iron',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='iron_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='isomalt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='lactitol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='magnesium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='maltitol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='mannitol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='monounsaturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='niacin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='nutrition_raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='pantothenate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='pantothenic_acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='polydextrose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='polyunsaturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='potassium_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='riboflavin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='saturated_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='saturated_fat_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='selenium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='serving_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='serving_size_raw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='serving_size_units',
            field=models.CharField(blank=True, choices=[('g', 'grams'), ('mL', 'millilitres')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='sodium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='sodium_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='sorbitol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='sugars',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='sugars_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='thiamine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_carbohydrate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_carbohydrate_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_fat_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='trans_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='trans_fat_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='vitamin_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='vitamin_a_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='vitamin_b12',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='vitamin_b6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='vitamin_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='vitamin_c_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='vitamin_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='vitamin_e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='xylitol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='zinc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition_available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
