# Generated by Django 2.2.4 on 2020-02-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200210_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='historicalnutritionfacts',
            name='total_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
