# Generated by Django 3.0.7 on 2020-06-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200616_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
