# Generated by Django 3.0.7 on 2020-07-28 14:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import flaim.database.models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200619_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('predicted_category', models.CharField(blank=True, max_length=500, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('model_verison', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='image_directory',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='item_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='manufacturer_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='parcel_dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='speciality',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproduct',
            name='units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amazonproductreview',
            name='review_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='amazonproductreview',
            name='reviewer_username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='frontofpacklabel',
            name='classified_image_path',
            field=models.ImageField(max_length=1500, upload_to=flaim.database.models.upload_fop_image),
        ),
        migrations.AlterField(
            model_name='frontofpacklabel',
            name='label_type',
            field=models.CharField(blank=True, choices=[('FC', 'FOOD_COLOURING')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalamazonproduct',
            name='image_directory',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalamazonproduct',
            name='item_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalamazonproduct',
            name='manufacturer_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalamazonproduct',
            name='parcel_dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalamazonproduct',
            name='speciality',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalamazonproduct',
            name='units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalloblawsproduct',
            name='upc_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalnutritionfacts',
            name='serving_size_raw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnutritionfacts',
            name='serving_size_units',
            field=models.CharField(blank=True, choices=[('g', 'grams'), ('mL', 'millilitres')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnutritionfacts',
            name='total_size',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='breadcrumbs_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='breadcrumbs_text',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='price_units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='store',
            field=models.CharField(choices=[('LOBLAWS', 'Loblaws'), ('WALMART', 'Walmart'), ('AMAZON', 'Amazon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalwalmartproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loblawsproduct',
            name='upc_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='serving_size_raw',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='serving_size_units',
            field=models.CharField(blank=True, choices=[('g', 'grams'), ('mL', 'millilitres')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionfacts',
            name='total_size',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlabelclassification',
            name='classification',
            field=models.CharField(blank=True, choices=[('N', 'NUTRITION'), ('I', 'INGREDIENTS'), ('O', 'OTHER')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='breadcrumbs_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='breadcrumbs_text',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(choices=[('LOBLAWS', 'Loblaws'), ('WALMART', 'Walmart'), ('AMAZON', 'Amazon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_path',
            field=models.ImageField(max_length=1500, unique=True, upload_to=flaim.database.models.upload_product_image),
        ),
        migrations.AlterField(
            model_name='scrapebatch',
            name='scraper_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapebatch',
            name='store',
            field=models.CharField(choices=[('LOBLAWS', 'Loblaws'), ('WALMART', 'Walmart'), ('AMAZON', 'Amazon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='walmartproduct',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='predicted_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.PredictedCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='predicted_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.PredictedCategory'),
        ),
    ]
