# Generated by Django 3.0.7 on 2020-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20200728_1028'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='database_pr_product_cf930e_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_code', 'most_recent'], name='database_pr_product_3b36bc_idx'),
        ),
    ]
