# Generated by Django 3.0.7 on 2020-08-12 17:58
from django.contrib.postgres.operations import TrigramExtension

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0006_auto_20200804_0916'),
    ]

    operations = [
        TrigramExtension()
    ]
