# Generated by Django 3.0.7 on 2020-08-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200812_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predictedcategory',
            old_name='confidence',
            new_name='confidence_1',
        ),
        migrations.RenameField(
            model_name='predictedcategory',
            old_name='predicted_category',
            new_name='predicted_category_1',
        ),
        migrations.AddField(
            model_name='predictedcategory',
            name='confidence_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictedcategory',
            name='confidence_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictedcategory',
            name='predicted_category_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='predictedcategory',
            name='predicted_category_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
