# Generated by Django 3.0.7 on 2020-08-24 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0009_auto_20200821_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedcategory',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predictedcategory',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
