# Generated by Django 3.0.7 on 2020-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20200824_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictedcategory',
            name='manual_category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
