# Generated by Django 3.0.7 on 2020-09-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_categoryproductcodemappingsupport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproductcodemappingsupport',
            options={'verbose_name': 'Category:Product Code Mapping', 'verbose_name_plural': 'Category:Product Code Mappings'},
        ),
        migrations.AlterModelOptions(
            name='predictedcategory',
            options={'verbose_name': 'Predicted Category', 'verbose_name_plural': 'Predicted Categories'},
        ),
    ]
