# Generated by Django 3.0.7 on 2020-09-11 17:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0013_auto_20200911_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PredictedCategory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='predicted_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='predicted_category',
            new_name='category',
        ),
    ]
