# Generated by Django 3.0.7 on 2020-09-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20200911_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='atwater_test_pass',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='atwater_test_pass',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
