# Generated by Django 3.0.7 on 2020-09-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20200911_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='model_verison',
            new_name='model_version',
        ),
    ]
