# Generated by Django 3.0.7 on 2020-09-28 18:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0021_auto_20200925_0911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignedSubcategory',
            new_name='Subcategory',
        ),
        migrations.RenameField(
            model_name='referencecategorysupport',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='referencecategorysupport',
            old_name='subcategory',
            new_name='subcategory_name',
        ),
    ]
