# Generated by Django 3.0.7 on 2020-10-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20201001_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencecategorysupport',
            options={'verbose_name': 'Reference Category', 'verbose_name_plural': 'Reference Categories'},
        ),
    ]
