# Generated by Django 3.0.7 on 2020-10-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20201002_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.ReferenceCategorySupport'),
        ),
    ]
