# Generated by Django 3.0.7 on 2020-11-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20201102_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapebatch',
            name='store',
            field=models.CharField(choices=[('LOBLAWS', 'Loblaws'), ('WALMART', 'Walmart'), ('VOILA', 'Voila'), ('GROCERYGATEWAY', 'Grocery Gateway'), ('AMAZON', 'Amazon')], max_length=50),
        ),
    ]
