# Generated by Django 3.0.7 on 2020-11-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20201105_1124'),
        ('database', '0030_auto_20201104_1141'),
    ]

    operations = [
    ]
