# Generated by Django 3.0.7 on 2021-03-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_auto_20201112_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='variety_pack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='variety_pack',
            field=models.BooleanField(default=False),
        ),
    ]
