# Generated by Django 3.0.7 on 2021-03-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_auto_20210302_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproductcodemappingsupport',
            name='variety_pack',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
