# Generated by Django 3.0.7 on 2021-05-18 15:56

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0034_auto_20210303_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='alcohol_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='biotin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='biotin_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='chloride',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='chloride_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='choline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='choline_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='chromium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='chromium_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='copper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='copper_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='folate_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='insoluble_fibre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='iodide',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='iodide_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='manganese',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='manganese_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='molybdenum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='molybdenum_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='niacin_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='omega6fattyacids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='pantothenate_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='riboflavin_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='selenium_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='soluble_fibre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='starch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='sugar_alcohols',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='sugar_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='thiamine_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='vitaminb12_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='vitaminb6_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='vitamind_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='vitamine_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='vitamink',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='vitamink_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalnutritionfacts',
            name='zinc_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='private_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='storage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='ultimate_company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='alcohol_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='biotin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='biotin_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='chloride',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='chloride_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='choline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='choline_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='chromium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='chromium_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='copper',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='copper_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='folate_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='insoluble_fibre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='iodide',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='iodide_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='manganese',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='manganese_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='molybdenum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='molybdenum_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='niacin_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='omega6fattyacids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='pantothenate_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='riboflavin_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='selenium_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='soluble_fibre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='starch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='sugar_alcohols',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='sugar_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='thiamine_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='vitaminb12_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='vitaminb6_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='vitamind_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='vitamine_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='vitamink',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='vitamink_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfacts',
            name='zinc_dv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='private_label',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ultimate_company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='store',
            field=models.CharField(choices=[('LOBLAWS', 'Loblaws'), ('WALMART', 'Walmart'), ('VOILA', 'Voila'), ('GROCERYGATEWAY', 'Grocery Gateway'), ('AMAZON', 'Amazon'), ('MINTEL', 'Mintel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(choices=[('LOBLAWS', 'Loblaws'), ('WALMART', 'Walmart'), ('VOILA', 'Voila'), ('GROCERYGATEWAY', 'Grocery Gateway'), ('AMAZON', 'Amazon'), ('MINTEL', 'Mintel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scrapebatch',
            name='store',
            field=models.CharField(choices=[('LOBLAWS', 'Loblaws'), ('WALMART', 'Walmart'), ('VOILA', 'Voila'), ('GROCERYGATEWAY', 'Grocery Gateway'), ('AMAZON', 'Amazon'), ('MINTEL', 'Mintel')], max_length=50),
        ),
        migrations.CreateModel(
            name='MintelProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image_directory', models.CharField(blank=True, max_length=500, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('bullets', models.TextField(blank=True, null=True)),
                ('dietary_info', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('allergens_warnings', models.TextField(blank=True, null=True)),
                ('nutrition_facts_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mintel_product', to='database.Product')),
            ],
            options={
                'verbose_name': 'Mintel Product',
                'verbose_name_plural': 'Mintel Products',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMintelProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('image_directory', models.CharField(blank=True, max_length=500, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('bullets', models.TextField(blank=True, null=True)),
                ('dietary_info', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('allergens_warnings', models.TextField(blank=True, null=True)),
                ('nutrition_facts_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Product')),
            ],
            options={
                'verbose_name': 'historical Mintel Product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='mintelproduct',
            index=models.Index(fields=['product'], name='database_mi_product_9237c1_idx'),
        ),
    ]
