# Generated by Django 3.0.7 on 2021-05-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_auto_20210518_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmintelproduct',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mintelproduct',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
