VALID_NUTRIENT_COLUMNS = [
    'calories',
    'sodium',
    'sodium_dv',
    'calcium',
    'calcium_dv',
    'totalfat',
    'totalfat_dv',
    'monounsaturated_fat',
    'polyunsaturated_fat',
    'saturatedfat',
    'saturatedfat',
    'saturatedfat_dv',
    'omega3fattyacids',
    'transfat',
    'transfat_dv',
    'potassium',
    'potassium_dv',
    'totalcarbohydrate',
    'totalcarbohydrate_dv',
    'dietaryfiber',
    'dietaryfiber_dv',
    'sugar',
    'sugar_dv',
    'protein',
    'cholesterol',
    'vitamina',
    'vitamina_dv',
    'vitaminc',
    'vitaminc_dv',
    'vitamind',
    'vitamine',
    'niacin',
    'vitaminb6',
    'folacin',
    'folate',
    'vitaminb12',
    'pantothenicacid',
    'pantothenate',
    'alcohol',
    'carbohydrate',
    'erythritol',
    'glycerol',
    'isomalt',
    'lactitol',
    'maltitol',
    'mannitol',
    'polydextrose',
    'sorbitol',
    'xylitol',
    'iron',
    'iron_dv',
    'riboflavin',
    'selenium',
    'magnesium',
    'phosphorus',
    'thiamine',
    'zinc'
]


EXPECTED_NUTRIENTS = (
    'Sugars',
    'Calories',
    'Sodium',
    'Calcium',
    'Total Fat',
    'Polyunsaturated Fat',
    'Monounsaturated Fat',
    'Saturated Fat',
    'Omega 3',
    'Trans. Fat',
    'Potassium',
    'Total Carbohydrate',
    'Dietary Fiber',
    'Protein',
    'Cholesterol',
    'Vitamin A',
    'Vitamin C',
    'Vitamin D',
    'Vitamin E',
    'Vitamin B6',
    'Folacin',
    'Vitamin B12',
    'Pantothenic Acid',
    'Pantothenate',
    'Alcohol',
    'Carbohydrate',
    'Erythritol',
    'Glycerol',
    'Isomalt',
    'Lactitol',
    'Maltitol',
    'Mannitol',
    'Polydextrose',
    'Sorbitol',
    'Xylitol',
    'Iron',
    'Riboflavin',
    'Folate',
    'Selenium',
    'Magnesium',
    'Niacin',
    'Phosphorus',
    'Thiamine',
    'Zinc'
)
