VALID_NUTRIENT_COLUMNS = [
    'calories',
    'sodium',
    'sodium_dv',
    'calcium',
    'calcium_dv',
    'total_fat',
    'total_fat_dv',
    'monounsaturated_fat',
    'polyunsaturated_fat',
    'saturated_fat',
    'saturated_fat',
    'saturated_fat_dv',
    'trans_fat',
    'trans_fat_dv',
    'potassium',
    'potassium_dv',
    'total_carbohydrate',
    'total_carbohydrate_dv',
    'dietary_fibre',
    'dietary_fibre_dv',
    'sugars',
    'sugars_dv',
    'protein',
    'cholesterol',
    'vitamin_a',
    'vitamin_a_dv',
    'vitamin_c',
    'vitamin_c_dv',
    'vitamin_d',
    'vitamin_e',
    'niacin',
    'vitamin_b6',
    'folacin',
    'folate',
    'vitamin_b12',
    'pantothenic_acid',
    'pantothenate',
    'alcohol',
    'carbohydrate',
    'erythritol',
    'glycerol',
    'isomalt',
    'lactitol',
    'maltitol',
    'mannitol',
    'polydextrose',
    'sorbitol',
    'xylitol',
    'iron',
    'iron_dv',
    'riboflavin',
    'selenium',
    'magnesium',
    'phosphorus',
    'thiamine',
    'zinc'
]


EXPECTED_NUTRIENTS = (
    'Sugars',
    'Calories',
    'Sodium',
    'Calcium',
    'Total Fat',
    'Polyunsaturated Fat',
    'Monounsaturated Fat',
    'Saturated Fat',
    'Trans. Fat',
    'Potassium',
    'Total Carbohydrate',
    'Dietary Fiber',
    'Protein',
    'Cholesterol',
    'Vitamin A',
    'Vitamin C',
    'Vitamin D',
    'Vitamin E',
    'Vitamin B6',
    'Folacin',
    'Vitamin B12',
    'Pantothenic Acid',
    'Pantothenate',
    'Alcohol',
    'Carbohydrate',
    'Erythritol',
    'Glycerol',
    'Isomalt',
    'Lactitol',
    'Maltitol',
    'Mannitol',
    'Polydextrose',
    'Sorbitol',
    'Xylitol',
    'Iron',
    'Riboflavin',
    'Folate',
    'Selenium',
    'Magnesium',
    'Niacin',
    'Phosphorus',
    'Thiamine',
    'Zinc'
)
