name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    services:
      postgres:
        image: postgres:10.12
        env:
          POSTGRES_USER: ${{ secrets.FLAIM_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.FLAIM_DB_PASSWORD }}
          POSTGRES_DB: flaim
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt
          npm i
          python manage.py collectstatic
      - name: Run Migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FLAIM_DB_USER: ${{ secrets.FLAIM_DB_USER }}
          FLAIM_DB_PASSWORD: ${{ secrets.FLAIM_DB_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
          DJANGO_DEBUG: True
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FLAIM_DB_USER: ${{ secrets.FLAIM_DB_USER }}
          FLAIM_DB_PASSWORD: ${{ secrets.FLAIM_DB_PASSWORD }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
        run: |
          pytest
